  export const sportsVenue = [
    {
      name: "Dream Sports Fields – Malad West",
      rating: 4.0,
      deferLink: "https://playo.page.link/dreamMalad",
      fullLink: "https://playo.co/venue/?venueId=dream-sports-fields-malad",
      address:
        "5RCM+XQC, Inorbit Rd, Malad, Mindspace, Malad West, Mumbai, Maharashtra 400064",
      avgRating: 4.0,
      ratingCount: 380,
      lat: 19.1724943,
      lng: 72.8344247,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4npgJAGqnpgoXij0qYVZ0fZK1PCMhGYAsy1soZuwnYyI-Vjkz_5y73Hu9CNcYJmtsnqYWawX0Ouy9LE0uhCg7__2U15t_inR1yjW2WHBcnV1tCaY2kkQvaTQ5vNvSD_PeLO5SJU53w=w533-h240-k-no",
      filter_by: ["Football", "Basketball", "Volleyball", "Futsal"],
      amenities: [
        "Changing Rooms 🚻",
        "Parking 🅿️",
        "Drinking Water 💧",
        "Restrooms 🚽",
      ],
      info: '\n \u00a0 \u00a0<h3>Dream Sports Fields – Malad West</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.0 [380]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Basketball, Volleyball, Futsal<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98765 12345<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/dreamMalad" target="_blank">Book Now</a><br/>\n',
    },
    {
      name: "The Arena – Andheri East",
      rating: 4.2,
      deferLink: "https://playo.page.link/arenaAndheri",
      fullLink: "https://playo.co/venue/?venueId=arena-andheri-east",
      avgRating: 4.2,
      ratingCount: 65,
      lat: 19.1138,
      lng: 72.8828,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Volleyball", "Cricket", "Badminton"],
      amenities: [
        "Cafeteria 🍔",
        "Locker Rooms 🔒",
        "Showers 🚿",
        "Parking 🅿️",
      ],
      info: '\n \u00a0 \u00a0<h3>The Arena – Andheri East</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.2 [65]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Volleyball, Cricket, Badminton<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 99220 56789<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/arenaAndheri" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4npZ9e3Di0EUxHCSF98V4EDtB_cJmbZ3AOa8tDpL34VOCd1QoelkmS3YqWZkMnT4bWn5H-5xw-LpMTLQFO4oXUoqaoF0Hi8yyK_pds99OjX2sUHs-QPHWdTf2AAyq_SrCULe_AJa=w408-h272-k-no",
      address:
        "Jitendra Industrial Estate, Andheri - Kurla Rd, Vijay Nagar Colony, Hanuman Nagar, Andheri East, Mumbai, Maharashtra 400093",
    },
    {
      name: "St. Andrews Turf – Bandra West",
      rating: 4.1,
      deferLink: "https://playo.page.link/andrewsBandra",
      fullLink: "https://playo.co/venue/?venueId=andrews-turf-bandra",
      avgRating: 4.1,
      ratingCount: 32,
      lat: 19.06,
      lng: 72.8365,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Cricket", "Tennis", "Hockey"],
      amenities: ["Floodlights 💡", "Restrooms 🚻", "Drinking Water 💧"],
      info: '\n \u00a0 \u00a0<h3>St. Andrews Turf – Bandra West</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.1 [32]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Cricket, Tennis, Hockey<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98112 34567<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/andrewsBandra" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/p/AF1QipM5Lll-w54b_3G_HvrLgjFWN2_BmHwnHHRlz8Q3=w408-h306-k-no",
      address:
        "St. Andrews School Ground, St Domnic Rd, Santosh Nagar, Bandra West, Mumbai, Maharashtra 400050",
    },
    {
      name: "Indian Football School – Churchgate",
      rating: 4.3,
      deferLink: "https://playo.page.link/ifsChurchgate",
      fullLink: "https://playo.co/venue/?venueId=ifs-churchgate",
      avgRating: 4.3,
      ratingCount: 45,
      lat: 18.9321,
      lng: 72.8323,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Table Tennis", "Squash", "Basketball"],
      amenities: ["Cafeteria 🍔", "Locker Rooms 🔒", "Parking 🅿️"],
      info: '\n \u00a0 \u00a0<h3>Indian Football School – Churchgate</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.3 [45]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Table Tennis, Squash, Basketball<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98200 12345<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/ifsChurchgate" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/p/AF1QipN7TkYSd-v_16TYoajbXwZgO49roOQSTctMvA0u=w408-h277-k-no",
      address:
        "Maharshi Karve Rd, Dr Ambedkar Statue Chowk Area, Churchgate, Mumbai, Maharashtra 400021",
    },
    {
      name: "Urban Sports – Vile Parle East",
      rating: 4.4,
      deferLink: "https://playo.page.link/urbanVileParle",
      fullLink: "https://playo.co/venue/?venueId=urban-vileparle",
      avgRating: 4.4,
      ratingCount: 120,
      lat: 19.1112,
      lng: 72.8476,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Badminton", "Tennis", "Futsal"],
      amenities: ["Changing Rooms 🚻", "Showers 🚿", "Restrooms 🚽"],
      info: '\n \u00a0 \u00a0<h3>Urban Sports – Vile Parle East</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.4 [120]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Badminton, Tennis, Futsal<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 99300 54321<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/urbanVileParle" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrIPbWq_xtmYn4XBCZtZeFXG6_1E2hFJx5HbvkGyFtkkIROcll6rm2EQZQvmFvg1OZCa5eMd9vwWJQfzhHspf8xCqnp6erZU4GpSpp4xaRXTAE3uEDZANkkJuhmZVoAI3OcSVVC=w426-h240-k-no",
      address:
        "Prabodhankar Thackeray Krida Sankul, Shahaji Raje Marg, Vishnu Prasad Society, Navpada, Vile Parle East, Vile Parle, Mumbai, Maharashtra 400057",
    },
    {
      name: "JS Turf – Borivali West",
      rating: 4.0,
      deferLink: "https://playo.page.link/jsturfBorivali",
      fullLink: "https://playo.co/venue/?venueId=js-turf-borivali",
      avgRating: 4.0,
      ratingCount: 10,
      lat: 19.2345,
      lng: 72.8543,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Hockey", "Cricket", "Volleyball"],
      amenities: ["Drinking Water 💧", "Restrooms 🚻", "Parking 🅿️"],
      info: '\n \u00a0 \u00a0<h3>JS Turf – Borivali West</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.0 [10]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Hockey, Cricket, Volleyball<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98765 67890<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/jsturfBorivali" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nqymiWYyLor5F5pcvPcJzfXYMsAcBNJROiskTD5L5RuOAiErpA-mtr46BCvjMSC_3C07vh1Yk7PJOFmMvsk47YP_2l__0_ODfqAKLQodNpDOzpXfPS2CuT5wLhfITbiELw88vdQxg=w408-h307-k-no",
      address:
        "New Link Rd, behind Om Lalita Petrol Pump, Eksar Village, I C Colony, Borivali West, Mumbai, Maharashtra 400103",
    },
    {
      name: "Astro Park – Lower Parel",
      rating: 4.2,
      deferLink: "https://playo.page.link/astroParel",
      fullLink: "https://playo.co/venue/?venueId=astro-park-lower-parel",
      avgRating: 4.2,
      ratingCount: 20,
      lat: 18.9974,
      lng: 72.817,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Tennis", "Basketball", "Squash"],
      amenities: ["Changing Rooms 🚻", "Showers 🚿", "Cafeteria 🍔"],
      info: '\n \u00a0 \u00a0<h3>Astro Park – Lower Parel</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.2 [20]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Tennis, Basketball, Squash<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98250 22446<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/astroParel" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrPKbkMn8WLRLwfJ0_dYYT6QFs68qK7z0MMF5MXH7_84OcOpjiuy3K1y_m9Tbr785pQR0vB3jlgMfW_rW-CYgCA1RvoRPVqjdZaCS_WXmrsjhf28Ndmn7AVAHIBVbPG-iSXYjo=w408-h306-k-no",
      address:
        "Raghuvanshi Mills, the terrace of Raghuvanshi Mansion Above Pinakin Entry Gate, Senapati Bapat Marg, Lower Parel, Mumbai, Maharashtra 400013",
    },
    {
      name: "HotFut – Dadar West",
      rating: 4.1,
      deferLink: "https://playo.page.link/hotFutDadar",
      fullLink: "https://playo.co/venue/?venueId=hotfut-dadar",
      avgRating: 4.1,
      ratingCount: 15,
      lat: 19.0198,
      lng: 72.8425,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Squash", "Badminton", "Futsal"],
      amenities: ["Parking 🅿️", "Restrooms 🚽", "Drinking Water 💧"],
      info: '\n \u00a0 \u00a0<h3>HotFut – Dadar West</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.1 [15]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Squash, Badminton, Futsal<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98190 11223<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/hotFutDadar" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/p/AF1QipMquf0TY7ODMt2qRk4ABM1vRBsAhn4Z86Pz5C-B=w408-h244-k-no",
      address:
        "Hind Service Industrial Premises Co-op Society, Veer Sawarkar Marg, Dadar West, Dadar, Mumbai, Maharashtra 400028",
    },
    {
      name: "HomeGround – Kandivali East",
      rating: 4.0,
      deferLink: "https://playo.page.link/homeGroundKandivali",
      fullLink: "https://playo.co/venue/?venueId=homeground-kandivali",
      avgRating: 4.0,
      ratingCount: 25,
      lat: 19.23,
      lng: 72.857,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Basketball", "Cricket", "Hockey"],
      amenities: ["Floodlights 💡", "Cafeteria 🍔", "Locker Rooms 🔒"],
      info: '\n \u00a0 \u00a0<h3>HomeGround – Kandivali East</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.0 [25]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Basketball, Cricket, Hockey<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98765 33456<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/homeGroundKandivali" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nr0G8Mto0QgOtQ7Woq4fyXRDWmg7G8D8CIDAKi6ciONriAEy0epNRdL_2O9cjg4APaSSEQcAvQER8kRUSNjrk4dntZ8HE2YfXWZ4LjilvGdG-JiqaevcyQRaKSxFV6Z39tkTow=w408-h544-k-no",
      address:
        "Thakur Stadium, Thakur, Thakur Village, Kandivali East, Mumbai, Maharashtra 400101",
    },
    {
      name: "Kunal Sports Arena – Goregaon",
      rating: 4.3,
      deferLink: "https://playo.page.link/kunalGoregaon",
      fullLink: "https://playo.co/venue/?venueId=kunal-arena-goregaon",
      avgRating: 4.3,
      ratingCount: 18,
      lat: 19.1471,
      lng: 72.846,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Volleyball", "Basketball", "Futsal"],
      amenities: ["Changing Rooms 🚻", "Showers 🚿", "Drinking Water 💧"],
      info: '\n \u00a0 \u00a0<h3>Kunal Sports Arena – Goregaon</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.3 [18]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Volleyball, Basketball, Futsal<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98222 99887<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/kunalGoregaon" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nqswM_MAVM4qJFW5ssiivd70t6KVYEpId9--LApYvkBd0f0TDZY0Merr8dd1TPF0iemEmO9mzxXyQSzrLDyOSauqElnlQvCUthvYuv6Vf9uwDZd08Mx7BKLHMHmjoEkrsKlaWB2=w408-h784-k-no",
      address:
        "Virwani Industrial Estate, Western Urban Rd, Hanuman Tekdi, Goregaon, Mumbai, Maharashtra 400063",
    },
    {
      name: "Battlefield – Little Angels Turf, Sion",
      rating: 3.7,
      deferLink: "https://playo.page.link/battleSion",
      fullLink: "https://playo.co/venue/?venueId=battle-little-angels-sion",
      avgRating: 3.7,
      ratingCount: 6,
      lat: 19.0183,
      lng: 72.845,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Badminton", "Table Tennis", "Futsal"],
      amenities: ["Restrooms 🚻", "Parking 🅿️", "Floodlights 💡"],
      info: '\n \u00a0 \u00a0<h3>Battlefield – Little Angels Turf, Sion</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 3.7 [6]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Badminton, Table Tennis, Futsal<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98760 44567<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/battleSion" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/p/AF1QipNIwU_w5PBT-sPnF0OEVXwUu6pQruSlR358jOHF=w408-h306-k-no",
      address:
        "Inside of Little Angels' International School, Shastri Lane, behind Manav Seva Sangh Hall, Sion West, Sion, Mumbai, Maharashtra 400019",
    },
    {
      name: "Battlefield – Andheri Chintamani Plaza",
      rating: 3.5,
      deferLink: "https://playo.page.link/battleAndheri",
      fullLink: "https://playo.co/venue/?venueId=battle-andheri-chintamani",
      avgRating: 3.5,
      ratingCount: 4,
      lat: 19.119,
      lng: 72.844,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Tennis", "Basketball", "Squash"],
      amenities: ["Drinking Water 💧", "Restrooms 🚽", "Showers 🚿"],
      info: '\n \u00a0 \u00a0<h3>Battlefield – Andheri Chintamani Plaza</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 3.5 [4]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Tennis, Basketball, Squash<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98760 55678<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/battleAndheri" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/p/AF1QipOkJ8otMFESqMnM12L7fOyhXoI_biUIJjEwQ8Ql=w408-h544-k-no",
      address:
        "Chintamani Plaza, Andheri - Kurla Rd, Mota Nagar, Andheri East, Mumbai, Maharashtra 400099",
    },
    {
      name: "Ileseum Raheja Futsal – Navi Mumbai",
      rating: 4.7,
      deferLink: "https://playo.page.link/rahejaFutsal",
      fullLink: "https://playo.co/venue/?venueId=raheja-futsal-navi",
      avgRating: 4.7,
      ratingCount: 3,
      lat: 19.077,
      lng: 73.032,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Table Tennis", "Badminton", "Volleyball"],
      amenities: ["Cafeteria 🍔", "Locker Rooms 🔒", "Parking 🅿️"],
      info: '\n \u00a0 \u00a0<h3>Ileseum Raheja Futsal – Navi Mumbai</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.7 [3]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Table Tennis, Badminton, Volleyball<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 97654 32109<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/rahejaFutsal" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4np4GoJGbe_bZ3njeiZh9q5_2qdXY90QFhKgHYhMOVIrVAKrIpTRtRh3Xvxf5lZlBdM9Uqk9M1ESKT8XttX4bYCeSAGVs1QGtM58waRpAdqR6XEOq7FD1EYDf-QNAbeqVeV4siuy=w408-h306-k-no",
      address:
        "Raheja District, MIDC Industrial Area, Shiravane, Juinagar, Navi Mumbai, Maharashtra 400705",
    },
    {
      name: "V4 Sports Arena – Bhandup",
      rating: 5.0,
      deferLink: "https://playo.page.link/v4Bhandup",
      fullLink: "https://playo.co/venue/?venueId=v4-sports-bhandup",
      avgRating: 5.0,
      ratingCount: 1,
      lat: 19.16,
      lng: 72.95,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Squash", "Basketball", "Tennis"],
      amenities: ["Floodlights 💡", "Changing Rooms 🚻", "Showers 🚿"],
      info: '\n \u00a0 \u00a0<h3>V4 Sports Arena – Bhandup</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 5.0 [1]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Squash, Basketball, Tennis<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98880 55667<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/v4Bhandup" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4npRBnE-H4G8r-f0eCj2cVXXfnAw5kRFM0X7ZAAAA7ExHiW9TMDLx-_XNggc7KoUeZ8SYZ-Zsl_B8iwVSOd_1dB9iuxCPMYOVm_aXwMHq8A0Agl7sN_cdWOQlSla2hDeoqjmxNRHvw=w426-h240-k-no",
      address:
        "Yashwant Smruti, ANAND NAGAR BARKHA CO-OPERATIVE GROUP HOUSING SOCIETY, Bhandup Village Rd, opp. Usha Nagar, Usha Nagar, Bhandup West, Mumbai, Maharashtra 400078",
    },
    {
      name: "The Sports Foundry – Bhandup",
      rating: 4.4,
      deferLink: "https://playo.page.link/foundryBhandup",
      fullLink: "https://playo.co/venue/?venueId=foundry-bhandup",
      avgRating: 4.4,
      ratingCount: 78,
      lat: 19.165,
      lng: 72.965,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Hockey", "Cricket", "Badminton"],
      amenities: [
        "Restrooms 🚻",
        "Drinking Water 💧",
        "Parking 🅿️",
        "Cafeteria 🍔",
      ],
      info: '\n \u00a0 \u00a0<h3>The Sports Foundry – Bhandup</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.4 [78]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Hockey, Cricket, Badminton<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 97654 12345<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/foundryBhandup" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/p/AF1QipM1xVclGfwkD1tB6EW5KFNp4lwOxgd88iXniFPJ=w408-h306-k-no",
      address:
        "Rolex Metal Industries Compound, Village Road, Lal Bahadur Shastri Marg, Subhash Nagar, Bhandup West, Mumbai, Maharashtra 400078",
    },
    {
      name: "Battlefield – Mulund West",
      rating: 5.0,
      deferLink: "https://playo.page.link/battleMulund",
      fullLink: "https://playo.co/venue/?venueId=battle-mulund-west",
      avgRating: 5.0,
      ratingCount: 2,
      lat: 19.164,
      lng: 72.956,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Volleyball", "Futsal", "Cricket"],
      amenities: ["Locker Rooms 🔒", "Showers 🚿", "Cafeteria 🍔"],
      info: '\n \u00a0 \u00a0<h3>Battlefield – Mulund West</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 5.0 [2]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Volleyball, Futsal, Cricket<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98700 11122<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/battleMulund" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4npbHRSxPCB1jneU_7iXFdkMz9NLqzKhBTRjnDcVR3EtUbiqDOfGJ3BMDqwNWaKUdxM-fxh4QqJeUCCXEs_Y5JlNIZAzqlWxxlVL519B5KwpD_r3gap-HXZMeHJ-4PqdoOCR8loV=w408-h306-k-no",
      address:
        "Minerva Industrial Estate, Plot No.112, near Hercules Hoist, Asha Nagar, Mulund West, Mumbai, Maharashtra 400080",
    },
    {
      name: "Force Playing Fields – Dahisar",
      rating: 5.0,
      deferLink: "https://playo.page.link/forceDahisar",
      fullLink: "https://playo.co/venue/?venueId=force-dahisar",
      avgRating: 5.0,
      ratingCount: 3,
      lat: 19.237,
      lng: 72.854,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Basketball", "Hockey", "Tennis"],
      amenities: [
        "Drinking Water 💧",
        "Restrooms 🚻",
        "Parking 🅿️",
        "Floodlights 💡",
      ],
      info: '\n \u00a0 \u00a0<h3>Force Playing Fields – Dahisar</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 5.0 [3]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Basketball, Hockey, Tennis<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98722 33445<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/forceDahisar" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4noYftW1G7dLPodkFqhlFtSqcv6Ptl1erNTJYx15JNkMKDyH3cl9NzAfNIMuWP-lDscB33v9AUP63lH0PkPYM-KDw7uB5qLDQmGjDeLCTiGF0AJS0OLJ6KT8LNE0kd3QlHmLyym5fg=w426-h240-k-no",
      address:
        "7V2F+39X, Suhasini Pawaskar Rd, Vaishali Nagar, Dahisar East, Mumbai, Maharashtra 400068",
    },
    {
      name: "Fr. Agnel Stadium – Vashi",
      rating: 4.5,
      deferLink: "https://playo.page.link/agnelVashi",
      fullLink: "https://playo.co/venue/?venueId=agnel-stadium-vashi",
      avgRating: 4.5,
      ratingCount: 50,
      lat: 19.0728,
      lng: 73.0104,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: [
        "Football",
        "Multi-sport",
        "Cricket",
        "Basketball",
        "Volleyball",
      ],
      amenities: [
        "Changing Rooms 🚻",
        "Showers 🚿",
        "Cafeteria 🍔",
        "Locker Rooms 🔒",
      ],
      info: '\n \u00a0 \u00a0<h3>Fr. Agnel Stadium – Vashi</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.5 [50]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Multi-sport, Cricket, Basketball, Volleyball<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98330 11234<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/agnelVashi" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrvIzSewic1CsPndd9I7fI99EcC9grwsKlo5N9eQLtOX8luJBGcIyRMLyAWiveca9bc5PldhThD0uOjy6Isp_KyOtlQYVL4p41-nJMM6NZrohgFHX25Bg5bkUbGT3Qg5JEvLFQ=w408-h306-k-no",
      address:
        "3XHV+P5M, Juhu Nagar, Sector 10A, Vashi, Navi Mumbai, Maharashtra 400703",
    },
    {
      name: "Cooperage Ground – Nariman Point",
      rating: 4.2,
      deferLink: "https://playo.page.link/cooperage",
      fullLink: "https://playo.co/venue/?venueId=cooperage-ground",
      avgRating: 4.2,
      ratingCount: 60,
      lat: 18.9226,
      lng: 72.821,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Hockey", "Cricket", "Tennis"],
      amenities: ["Parking 🅿️", "Restrooms 🚻", "Drinking Water 💧"],
      info: '\n \u00a0 \u00a0<h3>Cooperage Ground – Nariman Point</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.2 [60]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Hockey, Cricket, Tennis<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98201 22334<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/cooperage" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4npnxQtR4oauRg3su2nxSkxTIjc1TKNQ1QNuiINMQDwd_4zGCicSYMj40zuwLgLvmkB7ivaRxxTxd7rJiiUsMiuE5WYhi-7QeZGmsCPgB9gNY5FlkPEmL7-d9E8yvhof5WDYp7AO=w408-h295-k-no",
      address:
        "Maharshi Karve Rd, Dr Ambedkar Statue Chowk Area, Nariman Point, Mumbai, Maharashtra 400021",
    },
    {
      name: "Oval Maidan – Churchgate",
      rating: 4.0,
      deferLink: "https://playo.page.link/ovalMaidan",
      fullLink: "https://playo.co/venue/?venueId=oval-maidan",
      avgRating: 4.0,
      ratingCount: 45,
      lat: 18.922,
      lng: 72.83,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: [
        "Football",
        "Recreation",
        "Badminton",
        "Cricket",
        "Basketball",
      ],
      amenities: ["Restrooms 🚻", "Drinking Water 💧", "Floodlights 💡"],
      info: '\n \u00a0 \u00a0<h3>Oval Maidan – Churchgate</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.0 [45]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Recreation, Badminton, Cricket, Basketball<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98190 55678<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/ovalMaidan" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4noyiiIjaBeEEA_nS8J1nnl0lds02Onc-GPycTOVPBzzJHdyvEJP4O7c8AZsCkdouXAk4ZC9OylF-nRmFcOCq6eehQfG63g6X2Q_KmSjxMHNZeVQBuATlrUxSmQens5CSs-Hqm0EtA=w408-h306-k-no",
      address:
        "140, महर्षी कर्वे, रोड, Mantralaya, Churchgate, Mumbai, Maharashtra 400032",
    },
    {
      name: "Azad Maidan – Fort",
      rating: 4.1,
      deferLink: "https://playo.page.link/azadMaidan",
      fullLink: "https://playo.co/venue/?venueId=azad-maidan",
      avgRating: 4.1,
      ratingCount: 50,
      lat: 18.9219,
      lng: 72.8313,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Cricket", "Basketball", "Hockey", "Volleyball"],
      amenities: ["Changing Rooms 🚻", "Restrooms 🚻", "Drinking Water 💧"],
      info: '\n \u00a0 \u00a0<h3>Azad Maidan – Fort</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.1 [50]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Cricket, Basketball, Hockey, Volleyball<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98200 33445<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/azadMaidan" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nonWR_WFhJTYXQYiJ6AvMHgC169jt6qe85zh4q7vs7ihnTfWIIId3iQqUjjARBXAFDu3VvVaLH6VeMkFDJMZitT3qIY6EAJ36Ze8Z86odY2sR43SncMo4j8chod99gM3_COQ48R1g=w408-h305-k-no",
      address: "Fort Mumbai, Maharashtra",
    },
    {
      name: "Oval Maidan’s Cross Ground",
      rating: 3.9,
      deferLink: "https://playo.page.link/crossMaidan",
      fullLink: "https://playo.co/venue/?venueId=cross-maidan",
      avgRating: 3.9,
      ratingCount: 40,
      lat: 18.9205,
      lng: 72.831,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Volleyball", "Tennis", "Futsal"],
      amenities: ["Parking 🅿️", "Restrooms 🚻", "Drinking Water 💧"],
      info: '\n \u00a0 \u00a0<h3>Cross Maidan – Churchgate</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 3.9 [40]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Volleyball, Tennis, Futsal<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98300 44556<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/crossMaidan" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrThMcTi7QyAn0TJgW2pZsDbJbekemaidxv6UjMzraNjc5hyWx2oFq68uXyHORmynxsIkGwQNdvSnnswTALU1_eDcNyLW-2-667dfj58mzqdrTyjGail0IY1P2I3mObWXjMFce7=w408-h306-k-no",
      address:
        "WRQH+5VR, New Marine Lines, Marine Lines, Mumbai, Maharashtra 400020",
    },
    {
      name: "Football Paradise – Kandivali",
      rating: 4.2,
      deferLink: "https://playo.page.link/footballParadise",
      fulllink: "https://playo.co/venue/?venueId=football-paradise-kandivali",
      avgRating: 4.2,
      ratingCount: 22,
      lat: 19.225,
      lng: 72.855,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Table Tennis", "Futsal", "Badminton"],
      amenities: [
        "Cafeteria 🍔",
        "Locker Rooms 🔒",
        "Showers 🚿",
        "Parking 🅿️",
      ],
      info: '\n \u00a0 \u00a0<h3>Football Paradise – Kandivali</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.2 [22]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Table Tennis, Futsal, Badminton<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98765 77889<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/footballParadise" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/p/AF1QipMbNj8xJyD4JDmOIbFxZUHNfrAAtiQcQfEzAoa-=w408-h306-k-no",
      address:
        "Goalster Sports Arena, next to Thakur Shyamnarayan School, Kandivali, Evershine Millennium Paradise, Thakur Village, Kandivali East, Mumbai, Maharashtra 400101",
    },
    {
      name: "Kick Turf – Powai",
      rating: 4.3,
      deferLink: "https://playo.page.link/kickPowai",
      fullLink: "https://playo.co/venue/?venueId=kick-turf-powai",
      avgRating: 4.3,
      ratingCount: 18,
      lat: 19.1176,
      lng: 72.905,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Squash", "Tennis", "Basketball"],
      amenities: ["Changing Rooms 🚻", "Restrooms 🚻", "Drinking Water 💧"],
      info: '\n \u00a0 \u00a0<h3>Kick Turf – Powai</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.3 [18]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Squash, Tennis, Basketball<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98822 33445<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/kickPowai" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nrXL_GGbkIraM6ePFhA3lYYe4tbCVsQspdKr_LbqMf3rjwhSfW7CGr9FRdFvEbOH__b9f899BDK_WvVu3wIUlP5tCo_xnw_4PIvxHjpF6wBiVrhS4MgIFgZdUU1hBlJ7aO3O7VorQ=w408-h306-k-no",
      address:
        "4W64+PX4, Kensington Rear Exit Road, Hiranandani Gardens, Powai, Mumbai, Maharashtra 400076",
    },
    {
      name: "Bravehearts Football Skool – Juhu",
      rating: 4.5,
      deferLink: "https://playo.page.link/braveMalad",
      fullLink: "https://playo.co/venue/?venueId=bravehearts-malad",
      avgRating: 4.5,
      ratingCount: 12,
      lat: 19.1643,
      lng: 72.828,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Badminton", "Volleyball", "Cricket"],
      amenities: ["Floodlights 💡", "Cafeteria 🍔", "Parking 🅿️"],
      info: '\n \u00a0 \u00a0<h3>Bravehearts Football Skool – Malad West</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.5 [12]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Badminton, Volleyball, Cricket<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98701 22334<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/braveMalad" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4no59YvwThLnMmMpyrgg4xt2GNW4rvx1Tqm7C638u493bXHBiBDRlZe6_OqUF8bVei1AgLwV0cgoQm_lGRjMcOvJiR7iOPCIBTmBJ9vFkNJeDTD8vG6tlwQp5bMmIHMuZzEstCk=w408-h272-k-no",
      address:
        "2, Birla Ln, Uditi Tarang Housing Colony, Janki Kutir, Juhu Tara, Juhu, Mumbai, Maharashtra 400049",
    },
    {
      name: "Agnel Astroturf – Vashi",
      rating: 4.5,
      deferLink: "https://playo.page.link/agnelVashi2",
      fullLink: "https://playo.co/venue/?venueId=agnel-stadium-vashi2",
      avgRating: 4.5,
      ratingCount: 30,
      lat: 19.0728,
      lng: 73.0104,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Multi-sport", "Cricket", "Basketball", "Tennis"],
      amenities: ["Restrooms 🚻", "Drinking Water 💧", "Locker Rooms 🔒"],
      info: '\n \u00a0 \u00a0<h3>RCF Ground – Chembur</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.5 [30]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Cricket<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98310 55678<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/agnelVashi2" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nq_dle3Gs4bEAG2dAF2gehBgG9f1K-FTL94z1QG93jlqz7PCIB6JPtW9yxWr_FPaEzhnSdMBtP3d1GczUUnbrLC5hCp4GhSqTKkVdWlM1BDeycj2RsE1W1DtWy7aUsaZOPvMxrk=w570-h240-k-no",
      address:
        "JN-2-B-2/76, Dr Mar Theophilus Marg, Juhu Nagar, Sector 9, Vashi, Navi Mumbai, Maharashtra 400703",
    },
    {
      name: "RCF Ground – Chembur",
      rating: 4.0,
      deferLink: "https://playo.page.link/rcfChembur",
      fullLink: "https://playo.co/venue/?venueId=rcf-ground-chembur",
      avgRating: 4.0,
      ratingCount: 5,
      lat: 19.067,
      lng: 72.9022,
      icon: "https://maps.google.com/mapfiles/kml/paddle/4-lv.png",
      filter_by: ["Football", "Multi-sport", "Cricket", "Hockey", "Volleyball"],
      amenities: [
        "Showers 🚿",
        "Changing Rooms 🚻",
        "Cafeteria 🍔",
        "Parking 🅿️",
      ],
      info: '\n \u00a0 \u00a0<h3>RCF Ground – Chembur</h3>\n \u00a0 \u00a0<strong>Ratings:</strong> 4.0 [5]<br/>\n \u00a0 \u00a0<strong>Sports:</strong> Football, Cricket<br/>\n \u00a0 \u00a0<strong>Phone:</strong> 98250 66555<br/>\n \u00a0 \u00a0<a href="https://playo.page.link/rcfChembur" target="_blank">Book Now</a><br/>\n',
      image:
        "https://lh3.googleusercontent.com/gps-cs-s/AC9h4nofkoMm4yAdcX7N_Vr5GLZCSGWG8ucPsVfVENhCi9y9RX3vRi6JxMW2Pzk-VNeKmA3zkOYE5AasqJYGH5V4lxw9HT7hg_IWeh39djTKEaojXXCIJUVi0rgsMIoyIPX-rnZPguki3g=w408-h306-k-no",
      address:
        "RCF Krida Sankul Sports Complex, RCF Colony, Chembur, Mumbai, Maharashtra 400074",
    },
  ];